Repository ValeriaDurruty/Clase_7_Tienda_Online, pull requests merged in 2024-07, with the labels that each got.

#2 Se agregó la categoría campera y sus detalles
  camperas.html
  productos_camperas/campera_argentina.html
  productos_camperas/campera_boca.html
  productos_camperas/campera_racing.html
  productos_camperas/campera_river.html
  public/img/campera_argentina.jpg
  public/img/campera_argentina1.jpg
  public/img/campera_boca.jpg
  public/img/campera_boca1.jpg
  public/img/campera_racing.jpg
  public/img/campera_racing1.jpg
  public/img/campera_river.jpg
  public/img/campera_river1.jpg
Labels: enhancement

#3 Pagina inicial
  README.md
  index.html
  productos-destacados.html
  promociones-del-dia.html
  public/css/destac-promos.css
  public/css/styles.css
  public/img/camiseta-argentina.jpg.jpg
  public/img/campera-hombre.jpg
  public/img/campera-mujer.jpg
  public/img/conjunto-hombre.jpg.jfif
  public/img/conjunto-mujer.jpg.jfif
  public/img/gorra.jpg
  public/js/script.js
Labels: bug, enhancement

#4 Se añade contraste
  camisetas.html
  camperas.html
  contacto.html
  index.html
  productos-destacados.html
  productos_camisetas/c_argentina.html
  productos_camisetas/c_gimnasia.html
  productos_camisetas/c_racing.html
  productos_camisetas/c_river.html
  productos_camperas/campera_argentina.html
  productos_camperas/campera_boca.html
  productos_camperas/campera_racing.html
  productos_camperas/campera_river.html
  promociones-del-dia.html
  public/css/style.css
  public/js/script.js
Labels: enhancement

#5 Cat gorros
  gorros.html
  productos_gorros/gorra_argentina.html
  productos_gorros/gorra_miami.html
  productos_gorros/gorro_boca.html
  productos_gorros/river.html
  public/img/Argentina_gorra.webp
  public/img/BOCA_jrs.webp
  public/img/Boc-A.webp
  public/img/Gorro_river.webp
  public/img/afa_escudo.webp
  public/img/boca-juniors.webp
  public/img/diagonal_argentina.webp
  public/img/gorrito_de_river.webp
  public/img/gorro_de_lana.webp
  public/img/gorro_lana.webp
  public/img/nuca_de_la_gorra.webp
  public/img/river-gorrito.webp
  public/img/river_gorro.webp
  public/img/seleccion-argentina.webp
Labels: enhancement

#6 Pagina inicial
  FETCH_HEAD
  gorros.html
  index.html
  productos-destacados.html
  productos_gorros/gorra_argentina.html
  productos_gorros/gorra_miami.html
  productos_gorros/gorro_boca.html
  productos_gorros/river.html
  promociones-del-dia.html
  public/css/destac-promos.css
  public/css/style.css
Labels: enhancement

#7 Agregados finales
  camisetas.html
  camperas.html
  contacto.html
  gorros.html
  index.html
  productos-destacados.html
  productos_camisetas/c_argentina.html
  productos_camisetas/c_gimnasia.html
  productos_camisetas/c_racing.html
  productos_camisetas/c_river.html
  productos_camperas/campera_argentina.html
  productos_camperas/campera_boca.html
  productos_camperas/campera_racing.html
  productos_camperas/campera_river.html
  productos_gorros/gorra_argentina.html
  productos_gorros/gorra_miami.html
  productos_gorros/gorro_boca.html
  productos_gorros/river.html
  promociones-del-dia.html
  public/css/styles.css
Labels: enhancement

#8 Documentación del proyecto
  CHANGELOG.md
Labels: documentation
